# Generated by Django 3.2.3 on 2021-07-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(null=True, verbose_name='Specifications'),
        ),
    ]
