# Generated by Django 3.2.3 on 2021-05-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='sd',
            field=models.BooleanField(default=True, verbose_name='Sd slot'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='sd_memory_max',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Maximum memory capacity'),
        ),
    ]
