# Generated by Django 3.2.3 on 2021-06-17 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_cart1_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart1',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='owner of the cart'),
        ),
    ]
