# Generated by Django 3.2.3 on 2021-07-02 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_name', models.CharField(max_length=100, verbose_name='Specification name')),
                ('spec_filter_name', models.CharField(max_length=50, verbose_name='Name for filter')),
                ('unit_of_measure', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit of measure')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='category')),
            ],
            options={
                'unique_together': {('category', 'spec_name', 'spec_filter_name')},
            },
        ),
        migrations.CreateModel(
            name='SpecificationValidator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_spec_value', models.CharField(max_length=100, verbose_name='Valid value')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='category')),
                ('spec_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.categoryspecification', verbose_name='Specification key')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product', verbose_name='Product')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.categoryspecification', verbose_name='Specification')),
            ],
        ),
    ]
